[tool.poetry]
name = "ami"
version = "0.1.0"
description = ""
authors = ["Mei Chen <meichen.mlc@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
marker-pdf = "^0.2.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
